services:
  postgres:
    image: postgres:15
    container_name: javafx_postgres
    environment:
      POSTGRES_DB: finance_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
